# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/lavrahq/cli
    steps:
      - checkout

      # Check if Build is Necessary
      - run:
          name: get semantic-release
          command: |
            curl \
              -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
      - run:
          name: determine version
          command: |
            ~/semantic-release \
              -ghr \
              -vf \
              -slug lavrahq/cli \
              -noci

      # Get Other Global Tools
      - run:
          name: get dep
          command: |
            go get \
              -u github.com/golang/dep/cmd/dep
      - run:
          name: get gox
          command: |
            go get \
              -u github.com/mitchellh/gox
      - run:
          name: get ghr
          command: |
            go get \
              -u github.com/tcnksm/ghr
      - run:
          name: get govvv
          command: |
            go get \
              -u github.com/ahmetb/govvv

      # Install Dependencies
      - run:
          name: ensure dep
          command: |
            dep ensure
      
      # Start Build
      - run:
          name: gox build
          command: |
            rm -rf dist/

            version=$(cat .version)
            ldflags=$(govvv -pkg github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/version -version $version -flags)

            gox \
              -os="linux darwin windows" \
              -arch="amd64 386" \
              -output="dist/lavra_{{.OS}}_{{.Arch}}" \
              -ldflags="$ldflags"
      
      - run:
          name: release
          command: |
            ghr $(cat .ghr) dist/